(function(){
'use strict';
const R=['C','C#','D','Eb','E','F','F#','G','Ab','A','Bb','B'],P={C:0,'C#':1,Db:1,D:2,'D#':3,Eb:3,E:4,F:5,'F#':6,Gb:6,G:7,'G#':8,Ab:8,A:9,'A#':10,Bb:10,B:11};
const Q=['','m','7','maj7','m7','sus2','sus4','add9','6','dim','aug'];
function tok(x){return String(x||'').trim().replace(/^[([\s]+|[)\],;|\s]+$/g,'')}
function chord(x){x=tok(x);return /^([A-G](?:#|b)?)(?:(?:maj|min|m|dim|aug|sus|add|omit|no|alt|M|Δ|°|\+|-)?(?:2|4|5|6|7|9|11|13|maj7|min7|m7|dim7|sus2|sus4|add9|add11|add13|#5|b5|#9|b9|#11|b13)?)*(?:\/[A-G](?:#|b)?)?$/.test(x)}
function chordLine(x){let a=String(x||'').trim().split(/\s+/).filter(Boolean);return a.length>0&&a.length<=24&&a.every(chord)}
function tr1(x,n){if(!chord(x))return x;let m=x.match(/^([A-G](?:#|b)?)(.*)$/);if(!m||P[m[1]]===undefined)return x;let r=R[(P[m[1]]+n+12)%12];let s=m[2].replace(/\/([A-G](?:#|b)?)/g,(z,b)=>P[b]===undefined?z:'/'+R[(P[b]+n+12)%12]);return r+s}
function transposeAny(x,n){x=String(x||'').trim();return chordLine(x)?x.split(/\s+/).map(v=>tr1(v,n)).join(' '):tr1(x,n)}
function parseLine(raw){let l=String(raw||'').replace(/\t/g,' ').trim();if(!l)return null;let ins=[];let plain=l.replace(/\[([^\]]+)\]/g,(z,c)=>{c=tok(c);if(chord(c)){ins.push(c);return ' '}return z}).replace(/\s+/g,' ').trim();if(ins.length)return{chord:ins.join(' '),lyric:plain};if(chordLine(l))return{chord:l.split(/\s+/).join(' '),lyric:''};let a=l.split(/\s+/),cs=[],i=0;while(i<a.length&&chord(a[i]))cs.push(tok(a[i++]));return cs.length?{chord:cs.join(' '),lyric:a.slice(i).join(' ')}:{chord:'',lyric:l}}
function section(x){let m=String(x||'').replace(/^\[|\]$/g,'').replace(/:$/,'').trim().match(/^(intro|verse|pre[- ]?chorus|chorus|refrain|bridge|tag|ad[- ]?lib|adlib|interlude|instrumental|outro|ending)(?:\s*(\d+))?$/i);if(!m)return null;let b=m[1].toLowerCase().replace(/pre[- ]?chorus/,'Pre-Chorus').replace(/ad[- ]?lib/,'Adlib');if(/^verse$/i.test(b))return'Verse '+(m[2]||'1');return b.charAt(0).toUpperCase()+b.slice(1)+(m[2]?' '+m[2]:'')}
function analyze(text){let sec={},ord=[],cur='Verse 1';function use(s){if(!sec[s]){sec[s]=[];ord.push(s)}cur=s}use(cur);String(text||'').replace(/\r/g,'').split('\n').forEach(raw=>{let l=raw.trim();if(!l)return;if(/^(key|tonality|capo|tuning|tempo)\s*[:=-]?/i.test(l))return;let s=section(l);if(s){use(s);return}let p=parseLine(l);if(p)sec[cur].push([p.chord,p.lyric])});ord=ord.filter(x=>sec[x]&&sec[x].length);return{sections:sec,order:ord.length?ord:['Verse 1']}}
function key(text,d){let m=String(text||'').match(/(?:^|\n)\s*(?:key|tonality)\s*[:=-]\s*([A-G](?:#|b)?)/i);if(m&&P[m[1]]!==undefined)return R[P[m[1]]];for(let s of d.order)for(let r of d.sections[s]){let z=tok(String(r[0]||'').split(/\s+/)[0]).match(/^([A-G](?:#|b)?)/);if(z&&P[z[1]]!==undefined)return R[P[z[1]]]}return'C'}
function family(k){let p=P[k]??0,ds=[0,2,4,5,7,9,11],qs=['','m','m','','','m','dim'],rom=['I','ii','iii','IV','V','vi','vii°'];return ds.map((d,i)=>({roman:rom[i],chord:R[(p+d)%12]+qs[i]}))}
function bank(){let m=document.getElementById('modal'),b=document.getElementById('modalBody');if(!m||!b)return;m.style.display='flex';b.innerHTML='<div class="row"><div><h2 style="margin:0">🎸 Chord Bank</h2><div class="muted">Chord recognition, families and transpose preview.</div></div><button class="btn" id="bankBack">Back</button></div><div class="card"><b>Recognized chord forms</b><div class="muted" style="margin:7px 0">Roots + qualities/extensions + slash bass.</div><div style="display:flex;gap:6px;flex-wrap:wrap">'+Q.map(q=>'<span class="badge">C'+q+'</span>').join('')+'<span class="badge">C/E</span><span class="badge">F#/A#</span></div></div><div class="card"><b>Major-key family</b><select id="bk" class="input" style="margin-top:8px;max-width:180px">'+R.map(x=>'<option>'+x+'</option>').join('')+'</select><div id="bf" style="display:grid;grid-template-columns:repeat(2,1fr);gap:7px;margin-top:10px"></div></div><div class="card"><b>Transpose preview</b><div class="controls" style="margin-top:8px"><input id="bc" class="input" value="G Am D/F#"><select id="bt" class="input" style="max-width:180px">'+R.map(x=>'<option>'+x+'</option>').join('')+'</select></div><div id="bp" style="margin-top:10px;font:bold 18px monospace"></div></div>';let bk=document.getElementById('bk'),bt=document.getElementById('bt'),bc=document.getElementById('bc');function rf(){document.getElementById('bf').innerHTML=family(bk.value).map(x=>'<div class="item" style="margin:0;padding:9px"><b>'+x.roman+'</b><span style="margin-left:auto;font-family:monospace">'+x.chord+'</span></div>').join('')}function rp(){let f=tok(bc.value.split(/\s+/)[0]).match(/^([A-G](?:#|b)?)/);let from=f&&P[f[1]]!==undefined?P[f[1]]:0;document.getElementById('bp').textContent=transposeAny(bc.value,(P[bt.value]-from+12)%12)}bk.onchange=rf;bt.onchange=rp;bc.oninput=rp;document.getElementById('bankBack').onclick=()=>{closeModal();openSearch()};rf();rp()}
function patch(){let os=window.openSearch;window.openSearch=function(){os();let r=document.getElementById('analysisResult');if(r&&!document.getElementById('chordBankBtn')){let x=document.createElement('button');x.id='chordBankBtn';x.type='button';x.className='btn';x.style='width:100%;margin-top:8px';x.textContent='🎸 Open Chord Bank';x.onclick=bank;r.parentNode.insertBefore(x,r)}};window.analyzeSong=function(){let title=(document.getElementById('importTitle')?.value||'').trim()||'Imported Song',artist=(document.getElementById('importArtist')?.value||'').trim()||'Unknown Artist',text=(document.getElementById('songText')?.value||'').trim(),out=document.getElementById('analysisResult');if(!text){out.innerHTML='<div class="card">Paste lyrics/chords first.</div>';return}let d=analyze(text);base={};d.order.forEach(s=>base[s]=d.sections[s]);arrangement=d.order.slice();activeSection=arrangement[0]||'';currentSongTitle=title;currentArtist=artist;currentKey=key(text,d);transposeSource=JSON.parse(JSON.stringify(base));let cc=Object.values(base).flat().filter(r=>r[0]).length,lc=Object.values(base).flat().filter(r=>r[1]).length;out.innerHTML='<div class="card"><b>Chord Bank analysis complete</b><div class="muted" style="margin:7px 0 12px">Key: <b>'+esc(currentKey)+'</b> • '+cc+' chord lines • '+lc+' lyric lines</div><div style="display:flex;gap:6px;flex-wrap:wrap;margin-bottom:10px">'+arrangement.map(esc).map(x=>'<span class="badge">'+x+'</span>').join('')+'</div><button type="button" class="btn primary" style="width:100%" onclick="finishImport()">✓ Open Analyzed Song</button><button type="button" class="btn" id="chordBankBtn" style="width:100%;margin-top:8px">🎸 Open Chord Bank</button></div>';document.getElementById('chordBankBtn').onclick=bank};window.transposeChord=transposeAny}
patch();window.ChordBank={isChordToken:chord,isChordLine:chordLine,parseLine,analyzeText:analyze,transposeAny,familyForKey:family,showChordBank:bank};
})();